name: Clean up PR

on:
    pull_request:
        types: [closed]
        branches:
            - develop

jobs:
    close_pull_request:
        if: github.event.repository.full_name == 'SpareBank1/designsystem' && github.event_name == 'pull_request' && github.event.action == 'closed' && !github.event.pull_request.head.repo.fork
        runs-on: ubuntu-latest
        name: Close Pull Request Job
        steps:
            - name: Close Pull Request
              id: closepullrequest
              uses: Azure/static-web-apps-deploy@v1
              with:
                  azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLACK_BEACH_0D62D0D03 }}
                  action: 'close'
