name: 'CI testing'

on:
    pull_request:
        branches: [develop]

jobs:
    test-ci:
        name: 'build, test, build overview'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '18'
            - run: npm install
            - run: npm run build
            - run: npm run lint
            - run: npm test -- --ci
            - name: Make component-overview
              run: GH_PUBLIC_URL=/ make -e -C component-overview/ ghpages
            - uses: actions/upload-artifact@v3
              with:
                  name: component-overview
                  path: component-overview/build/
