name: Test CI

on:
    pull_request:
        branches: [develop]

jobs:
    test-ci:
        name: Build, test, and build component-overview
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 18
            - run: npm install
            - run: npm run build
            - run: npm run lint
            - run: npm test -- --ci
            - name: Make component-overview
              run: GH_PUBLIC_URL=/ make -e -C component-overview/ ghpages
            - uses: actions/upload-artifact@v3
              with:
                  name: component-overview-pr-${{ github.event.number }}
                  path: component-overview/build/
